title: Kazzle Dazzle
description: Yet another bedazzling blog of mine.
show_downloads: true

# baseurl: "/kazzle-dazzle" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "kazzle-dazzle.com.au" # change this to the base hostname & protocol for your site

google_analytics:
# kazzle-dazzle date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
kazzle-dazzle:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Karen Bajador"
image: /thumbnail-jumbo.png
twitter:
  username: kmb_v
github:
  owner_name: karenbajador
  owner_url: https://github.com/karenbajador  
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # kazzle-dazzle
  #authors: lorepirri
#  admins: